[TM-29] Add organizer/list endpoint fetching.
pw-software-engineering/2023-konfetti pull request #60
Opened 2023-04-05 18:50 UTC by faliszewskii

![image](https://user-images.githubusercontent.com/74872004/230175580-5d449051-22f5-4b7c-866b-1fb6cae34b56.png)

![image](https://user-images.githubusercontent.com/74872004/230176791-59983431-08ea-4080-934d-6740f004a7e5.png)

2023-04-06 11:32 UTC, gorkaj submitted a review, later dismissed
Nice job, feature seems to be working fine (only reading through mockito and tests scared me off)

2023-04-06 11:33 UTC, gorkaj commented on src/front/ticketer/lib/backend_communication/logic/communication.dart
> +      dio.options.contentType = Headers.jsonContentType;
Could you please add the same line in standard postCall method? Just as a workaround for login bugs, we will implement nicer solution in TM-84

2023-04-18 09:05 UTC, bjadczak requested changes
Remove mocks and re write tests using methods presented in #79 and #72

Also rebase this PR, in order to remove conflicts

2023-04-20 22:12 UTC, bjadczak approved these changes

2023-04-20 22:48 UTC, merged